CREATE TABLE IF NOT EXISTS SAM_ENTITY
(
    ID          BIGINT(20)      PRIMARY KEY AUTO_INCREMENT,
    NAME        VARCHAR(255)    NOT NULL,
    DESCRIPTION TEXT            NULL,
    CREATED_AT  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)